# fly.toml app configuration file generated for web-prog-beadando on 2023-09-28T16:58:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "web-prog-beadando"
primary_region = "otp"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
